- name: Create letsencrypt directory
  file:
    name: /var/www/letsencrypt
    state: directory

- name: Remove default nginx config
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Nginx http config
  template:
    src: http.j2
    dest: /etc/nginx/sites-enabled/http
  register: nginx_http_config

- name: Restart nginx for letsencrypt
  service:
    name: nginx
    state: restarted
  when: nginx_http_config.changed

- name: Create letsencrypt certificate
  shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m dan@tangledhelix.com --agree-tos -d {{ inventory_hostname }}
  args:
    creates: /etc/letsencrypt/live/{{ inventory_hostname }}

- name: Generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem

- name: Nginx pptools site config
  template:
    src: pptools.j2
    dest: /etc/nginx/sites-enabled/pptools
    mode: 0644
    owner: root
    group: root
  notify: Restart nginx

- name: Make sure nginx service is running
  systemd:
    state: started
    enabled: true
    name: nginx
