- name: Install uwsgi configuration file
  template:
    src: pptools.ini.j2
    dest: /etc/uwsgi/apps-enabled/pptools.ini
    mode: 0644
    owner: root
    group: root
  notify: Restart uwsgi

- name: Make sure uwsgi service is running
  systemd:
    state: started
    enabled: true
    name: uwsgi
