- name: "Create pptools directory"
  file:
    path: "{{ base_dir }}"
    state: "directory"
  tags:
    - "app_setup"

- name: "Git checkout of pptools code"
  git:
    repo: "{{ pptools_git_url }}"
    dest: "{{ base_dir }}"
    version: "{{ pptools_git_branch }}"
  notify: "Restart uwsgi"
  tags:
    - "app_setup"

- name: "Create temp directory"
  file:
    path: "{{ base_dir }}/wsgi/temp"
    state: "directory"
    mode: "0755"
    owner: "www-data"
    group: "www-data"
  tags:
    - "app_setup"

- name: "Create uploads directory"
  file:
    path: "{{ base_dir }}/wsgi/temp/uploads"
    state: "directory"
    mode: "0755"
    owner: "www-data"
    group: "www-data"
  tags:
    - "app_setup"

- name: "Create projects directory"
  file:
    path: "{{ base_dir }}/wsgi/projects"
    state: "directory"
    mode: "0755"
    owner: "www-data"
    group: "www-data"
  tags:
    - "app_setup"
